//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int order_id { get; set; }
        public string order_name { get; set; }
        public string description { get; set; }
        public int created_by { get; set; }
        public int assigned_to { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime due_date { get; set; }
        public byte status { get; set; }
    
        public virtual User Manager { get; set; }
        public virtual User Employee { get; set; }
    }
}
